

name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        type: choice
        options: [qa, dev, uat]
        default: qa
        required: true
      suiteXmlFile:
        description: "TestNG XML File"
        type: choice
        options: [testng.xml, smoke.xml, regression.xml]
        default: testng.xml
        required: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test Automation Framework
      run: mvn test -DsuiteXmlFile="${{ github.event.inputs.suiteXmlFile }}" -Denv="${{ github.event.inputs.env }}"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Surefire Reports
        path: target/surefire-reports/
        retention-days: 10
      

